version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.0.0
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.0.28
    - 6.1.18
    - 6.2.0-alpha.33
    - 6.2.0-beta.10
    - 6.2.0-beta.14
    - 6.2.0-beta.4
    - 6.2.0-rc.11
    - 6.2.0-rc.6
    - 6.2.2
    - 6.2.7
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.0.28
    - 6.2.0-alpha.33
    - 6.2.0-beta.10
    - 6.2.0-beta.14
    - 6.2.0-beta.4
    - 6.2.0-rc.11
    - 6.2.0-rc.6
    - 6.2.2
    - 6.2.7
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.10.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.2.0-alpha.33
    - 6.2.0-beta.10
    - 6.2.0-beta.14
    - 6.2.0-beta.4
    - 6.2.0-rc.11
    - 6.2.0-rc.6
    - 6.2.2
    - 6.2.7
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ts-loader
    versions:
    - 8.0.18
    - 8.1.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.4
    - 2.1.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
    - 0.30.0
  - dependency-name: rollup-plugin-peer-deps-external
    versions:
    - 2.2.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - 4.2.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: commitizen
    versions:
    - 4.2.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: cz-conventional-changelog
    versions:
    - 3.3.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 14.0.0
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
